#libraries
import sys
import random
from PyQt5.QtWidgets import QApplication, QWidget, QVBoxLayout, QLabel, QPushButton, QHBoxLayout
from PyQt5.QtCore import Qt
'''

written by gokay sirin | github.com/gokayysirin

basarilar dilerim

'''
class VocabularyApp(QWidget):
    def __init__(self):
        super().__init__()

        # Kelimeler
        self.words = [
            ("Abandon", "Terk etmek"),
            ("Abundant", "Bol"),
            ("Accumulate", "Biriktirmek"),
            ("Adequate", "Yeterli"),
            ("Advance", "İlerlemek"),
            ("Advocate", "Savunmak"),
            ("abandon", "(1) (birini) terk etmek (= leave) (2) bir şeyden vazgeçmek (= give up)"),
            ("abbreviate", "(1) kısaltmak, özetlemek (2) (matematikte) sadeleştirmek"),
            ("abolish", "(toplumdaki tabuları) yıkmak, sona erdirmek (= do away with)"),
            ("absorb", "içine çekmek, emmek"),
            ("abstain from", "(alkol, ilaç vb) --- den sakınmak/ uzak durmak (= avoid from) !"),
            ("abundance", "bolluk, bereket"),
            ("abundant", "bol, bereketli"),
            ("accelerate", "hızlandırmak, ivme kazandırmak *** accelerator = gaz pedalı"),
            ("accept", "kabul etmek, razı olmak"),
            ("access", "erişmek, ulaşmak"),
            ("accessible to", "ulaşılabilir, erişilebilir"),
            ("accommodate", "(misafir, konuk vb) ağırlamak (= put up)"),
            ("accompany", "(1) eşlik etmek, arkadaşlık etmek (= escort) (2) beraber bulunmak ya da bir arada gözükmek (* Pain and fever accompany inflammatory diseases)"),
            ("accomplish", "başarmak (= achieve)"),
            ("accumulate", "(1) birikmek, çoğaltmak (2) biriktirmek, yığmak"),
            ("accuracy", "doğruluk, kesinlik"),
            ("accurate", "doğru, hatasız, eksiksiz bir şekilde (= precise, correct)"),
            ("accurately", "doğru, hatasız, eksiksiz bir şekilde (= precisely, correctly)"),
            ("accuse (of)", "birini bir şeyle suçlamak, itham etmek"),
            ("achieve", "başarmak, yerine getirmek"),
            ("acknowledge as", "(1) kabul etmek, --- olarak tanımak (2) (mektup, mesaj vb) aldığını gönderen kişiye bildirmek"),
            ("acquainted with", "aşina olmak, haberdar olmak (= familiar with)"),
            ("acquire", "(dil, miras, huy vb) edinmek, kazanmak (= obtain, attain) (She acquired a huge fortune.) ( I acquired Turkish but I learned English in school.)"),
            ("acquisition", "edinim"),
            ("activity", "faaliyet, aktivite *** activist = bir fikrin aktif destekçisi (= supporter)"),
            ("adapt", "bir şeye uyarlamak, uydurmak (= adjust)"),
            ("addict", "bağımlı, tiryaki *** drug addict = eroin bağımlısı"),
            ("addiction to", "bağımlılık, tiryakilik"),
            ("addition", "ilave, ek"),
            ("additionally", "ayrıca, bunun yanı sıra, buna ilaveten (= furthermore, moreover)"),
            ("adequately", "yeterli bir şekilde (= sufficiently)"),
            ("adjust", "(1) uyarlamak (= adapt) (2) alışmak (= get used to)"),
            ("adjustment", "düzeltme,intibak, uyma"),
            ("administer", "(1) idare etmek, yönetmek (2) (damardan ilaç vb) vermek, sağlamak"),
            ("admire", "hayran olmak"),
            ("admit", "kabullenmek, itiraf etmek"),
            ("adopt", "(1) evlat edinmek (= take up) (2) (önlem, tedbir vb) almak (adopt measure) (3) (başkasına ait bir şeyi) benimsemek (dil, din vb)"),
            ("adore", "çok sevmek, tapmak"),
            ("adverse", "zıt, kötü"),
            ("advocate", "(1) savunmak (= defend) (2) desteklemek (= support)"),
            ("affect", "etkilemek (= influence)"),
            ("aggravate", "gittikçe kötüye gitmek, fenalaşmak (= deteriorate, worsen)"),
            ("aggressive", "saldırgan"),
            ("aid", "yardım etmek (= help)"),
            ("alien (to)", "yabancı"),
            ("alongside", "yanında, bitişiğinde (beside, next to)"),
            ("alter", "değiştirmek (= change)"),
            ("alteration", "değişiklik"),
            ("amazing", "şaşırtıcı, hayran bırakıcı (= astonishing)"),
            ("amend", "değişiklik yapmak (kanunda düzenleme yapmak anlamındaki gibi)"),
            ("amendment", "değişiklik, (kanun vb) üzerinde değişiklik yapmak (= alteration)"),
            ("amusing", "eğlenceli, zevkli"),
            ("announce", "anons etmek, ilan etmek (= give out, declare)"),
            ("anticipate", "ummak, beklemek"),
            ("apologize", "özür dilemek (apologize to someone for something)"),
            ("appalling", "korkunç (= dreadful, horrendous)"),
            ("appointment", "(1) atama, tayin (2) randevu (= rendezvous)"),
            ("appreciate", "(1) takdir etmek, değerini bilmek (2) anlamak, farkına varmak"),
            ("approach", "(1) (zaman/mesafe bakımından birine/bir şeye) yaklaşmak (* Do not approach with fire!) (2) (bankaya/yüksek bir mevkiye vb) müracaatta bulunmak, ricada bulunmak (* She approached the bank for a loan)"),
            ("appropriately", "uygun olarak (= suitably)"),
            ("approve of", "onaylamak, uygun bulmak, tasvip etmek"),
            ("arrange", "düzenlemek, ayarlamak (toplantı, randevu vb)"),
            ("artefact", "insan eliyle yapılmış (sanat)"),
            ("ascend", "yukarı çıkmak, yükselmek, tırmanmak (= go up / climb up)"),
            ("ask for", "ricada bulunmak, bir şey istemek"),
            ("aspire", "şiddetle arzu etmek, çok istemek (* I’ve always aspired to be a singer)"),
            ("assemble", "(1) bir araya getirmek, toplamak (= gather) (2) monte etmek (= put up)"),
            ("assess", "değerlendirmek (= evaluate)"),
            ("assign", "atamak, tayin etmek, görevlendirmek (= appoint)"),
            ("assist somebody in something", "birine bir konuda yardım etmek"),
            ("associate", "(zihninde insanlar/eşyalar arasında) çağrışım yapmak, çağrıştırmak * I always associate the smell of baking with my childhood.) (2) (kötü yolda olan veya kötü alışkanlıkları olan insanlarla) arkadaşlık yapmak, düşüp kalkmak (* Don’t associate with those glue-sniffers.)"),
            ("assume", "(1) elinde delil olmadan bir şeyin doğru olduğunu düşünmek veya kabul etmek, farz etmek (= conclude) (2) (sorumluluk/vebal vb) üstlenmek, üzerine almak (= take on) (* I temporarily assumed the responsibility for her)"),
            ("assure", "birine teminat vermek, emin kılmak, garanti vermek"),
            ("astonishment", "şaşırtmak, şaşırmak (= amazement, bewilderment)"),
            ("attach", "iliştirmek, eklemek (= enclose)"),
            ("attack", "saldırmak, saldırı"),
            ("attain", "elde etmek, erişmek (= gain, obtain)"),
            ("attainment", "ulaşmak, erişmek"),
            ("attend", "iştirak etmek, katılmak"),
            ("attribute", "(bir sebebe/nedene) dayandırmak (= base on/upon)"),
            ("auditorium", "dinlenme/izleme salonu, seyircilerin oturduğu bölüm"),
            ("available", "mevcut, var olan"),
            ("avert", "(1) olmasını önlemek (2) başka yöne çevirmek (trafik akışını vb)"),
            ("avoidable", "kaçınılabilir, engellenebilir"),
            ("award", "ödül"),
            ("backward", "geri kalmış, geriye doğru"),
            ("badly in need of", "bir şeye/birine çok muhtaç olmak"),
            ("barely", "(1) hemen hemen hiç, neredeyse hiç (2) güçlükle (= hardly, scarcely)"),
            ("bargain", "(1) pazarlık, anlaşma (2) pazarlık etmek (3) kelepir, ucuz eşya"),
            ("barren", "kurak, verimsiz (= infertile, arid)"),
            ("basic", "temel (= essential, fundamental)"),
            ("bazaar", "pazar, alışveriş yeri"),
            ("behave", "davranmak"),
            ("believe", "inanmak"),
            ("belongings", "birinin kişisel eşyaları (= possessions)"),
            ("beloved", "sevgili, hazret"),
            ("bitingly satirical", "aşırı alaycı, insafsızca eleştirme"),
            ("bizarre", "tuhaf, acayip (= strange, weird)"),
            ("blanket", "battaniye"),
            ("blaze", "(1) ateş, alev, yangın (2) parlamak"),
            ("bolt", "fırlayıp kaçmak, tabanları yağlamak"),
            ("branch", "(1) dal, budak (2) şube, departman"),
            ("brand", "marka, etiket"),
            ("brave", "cesur, yürekli"),
            ("breakdown", "çöküş, parçalanma, bozulma"),
            ("breathe", "nefes almak"),
            ("breathe out", "nefes vermek"),
            ("breathtaking", "nefes kesici, heyecan verici"),
            ("brief", "kısa, öz"),
            ("brilliant", "parlak, zeki, muhteşem"),
            ("broadcast", "yaymak, yayım yapmak"),
            ("build", "inşa etmek"),
            ("building", "yapı, bina"),
            ("bunch", "demet, salkım, grup"),
            ("burden", "yük, sorumluluk"),
            ("business", "iş, ticaret"),
            ("capacity", "kapasite, alım gücü"),
            ("capital", "(1) ana sermaye (2) başkent"),
            ("caution", "dikkat, ihtiyat, temkin"),
            ("celebrate", "kutlamak"),
            ("centenarian", "yüzyıl yaşamış kişi"),
            ("chaotic", "kaotik, karmaşık"),
            ("clarify", "netleştirmek, açıklamak"),
            ("classify", "sınıflandırmak"),
            ("climate", "iklim"),
            ("collaborate", "iş birliği yapmak"),
            ("collection", "koleksiyon"),
            ("collide", "çarpışmak, çarpışmak (= bump)"),
            ("comb", "tarak"),
            ("command", "komut, emir"),
            ("commit", "(1) işlemek, (bir suç) işlemek, yapmak (2) kendini adamak, taahhüt etmek (3) (kendi adına) kendini ifade etmek"),
            ("committee", "komite"),
            ("companion", "arkadaş, yoldaş"),
            ("compensate", "telafi etmek, karşılamak"),
            ("complain", "şikayet etmek"),
            ("complete", "(1) tamamlamak (2) eksiksiz, tam"),
            ("compose", "(1) (bir müzik parçası) bestelemek (2) bir araya getirmek, oluşturmak (= formulate)"),
            ("compound", "bileşik (kimyasal), bir araya getirmek"),
            ("concentration", "yoğunlaşma, dikkati toplama"),
            ("concept", "kavram, fikir"),
            ("conclude", "sonuçlandırmak, sona ermek"),
            ("conduct", "(1) yönlendirmek, idare etmek (2) davranış"),
            ("conference", "konferans"),
            ("confidence", "güven, itimat"),
            ("conflict", "(1) çatışma, anlaşmazlık (2) çatışmak"),
            ("confusion", "kafa karışıklığı, karmaşa"),
            ("consent", "(1) rıza, izin (2) onay vermek (= approve)"),
            ("consequence", "sonuç, etki, netice"),
            ("considerable", "kayda değer, önemli"),
            ("consistent", "tutarlı, kararlı"),
            ("constant", "sabit, değişmez, sürekli"),
            ("consultation", "danışma, istişare"),
            ("consume", "tüketmek, harcamak"),
            ("contact", "iletişim, temas, irtibat, temasta bulunmak"),
            ("contain", "içermek, kapsamak"),
            ("contemporary", "çağdaş, modern"),
            ("contrast", "(1) karşılaştırmak, tezat oluşturmak (2) tezat, zıtlık"),
            ("contribute", "katkıda bulunmak"),
            ("convince", "ikna etmek"),
            ("cooperate", "iş birliği yapmak"),
            ("coordinate", "koordine etmek"),
            ("core", "öz, merkez"),
            ("correlate", "ilişki kurmak, bağ kurmak"),
            ("correspond", "(1) birbirine uymak, karşılık gelmek (2) yazışmak"),
            ("cost", "maliyet, masraf"),
            ("counsel", "tavsiye, danışmanlık, avukat"),
            ("counter", "karşı, tezgah, (1) çelişmek, karşı gelmek (2) önlemek"),
            ("courage", "cesaret, yürek"),
            ("create", "yaratmak, oluşturmak"),
            ("creature", "yaratık"),
            ("credit", "kredi, itibar, (1) saygı göstermek, itibar etmek (2) (+ to = birine bir şeyi) atfetmek"),
            ("crisis", "kriz, buhran"),
            ("critical", "eleştirel, kritik, önemli"),
            ("criticize", "eleştirmek"),
            ("crucial", "çok önemli"),
            ("culture", "kültür, medeniyet"),
            ("cure", "(1) tedavi, ilaç (2) tedavi etmek"),
            ("curious", "meraklı, ilginç"),
            ("current", "(1) mevcut (2) akıntı, akım (3) akı (deniz, nehir vb)"),
            ("custom", "(1) gelenek, görenek (2) (kişisel) ihtiyaçları gereği uyarlamak"),
            ("data", "veri"),
            ("decay", "çürümek, bozulmak, dağılmak"),
            ("decision", "karar, hüküm"),
            ("declare", "açıklamak, ilan etmek"),
            ("decline", "(1) reddetmek (2) düşmek, azalmak"),
            ("decrease", "azaltmak, eksiltmek"),
            ("deduce", "sonuç çıkarmak, anlamına gelmek"),
            ("defend", "savunmak, korumak"),
            ("define", "tanımlamak"),
            ("deliberate", "kasti, bilerek (2) tartışmak, düşünmek"),
            ("depend on", "bağlı olmak"),
            ("depict", "tasvir etmek, resmetmek"),
            ("derive", "(1) elde etmek (2) kaynaklanmak"),
            ("derive from", "--- dan kaynaklanmak"),
            ("description", "tanım, açıklama"),
            ("desire", "arzu, istek"),
            ("despair", "umutsuzluk, karamsarlık"),
            ("despite", "-e rağmen"),
            ("detail", "detay, ayrıntı"),
            ("determine", "belirlemek"),
            ("develop", "(1) geliştirmek (2) ilerlemek"),
            ("devote", "(zaman/güç vb) adamak, vermek"),
            ("differentiate", "ayırt etmek, farklılık göstermek"),
            ("dignity", "onur, haysiyet, saygınlık"),
            ("diminish", "azalmak, eksilmek"),
            ("direct", "doğrudan, yönlendirmek"),
            ("disclose", "açığa çıkarmak, ifşa etmek"),
            ("discomfort", "rahatsızlık"),
            ("discover", "keşfetmek"),
            ("discuss", "tartışmak"),
            ("disease", "hastalık"),
            ("display", "sergilemek, göstermek"),
            ("distinct", "ayrı, belirgin"),
            ("distinguish", "ayırt etmek"),
            ("distract", "dikkatini dağıtmak"),
            ("distribute", "dağıtmak"),
            ("document", "belgelendirmek, doküman"),
            ("dominate", "hâkim olmak, egemen olmak"),
            ("dramatic", "dramatik, abartılı"),
            ("draw", "çizmek, çekmek (to draw)"),
            ("duration", "süre, müddet"),
            ("dynamic", "dinamik, canlı, hareketli"),
            ("eager", "hevesli, istekli"),
            ("ease", "rahatlık, hafifletmek"),
            ("effective", "etkili, verimli"),
            ("efficiency", "verimlilik"),
            ("effort", "çaba, gayret"),
            ("elevate", "yükseltmek, artırmak"),
            ("eliminate", "ortadan kaldırmak"),
            ("embark on", "(yeni bir işe) başlamak"),
            ("emerge", "ortaya çıkmak"),
            ("emphasize", "vurgulamak, altını çizmek"),
            ("enable", "olanak vermek, sağlamak"),
            ("encounter", "karşılaşmak, rastlamak"),
            ("encourage", "cesaret vermek, teşvik etmek"),
            ("enhance", "geliştirmek, artırmak"),
            ("ensure", "garanti etmek, sağlamak"),
            ("enter", "girmek"),
            ("establish", "kurmak, tesis etmek"),
            ("evaluate", "değerlendirmek"),
            ("evolve", "evrim geçirmek, gelişmek"),
            ("example", "örnek, örnekleme"),
            ("exceed", "aşmak, geçmek"),
            ("exclude", "dışlamak, hariç tutmak"),
            ("excuse", "özür, bahane"),
            ("exhibit", "sergilemek, sergi"),
            ("exist", "var olmak, mevcut olmak"),
            ("expand", "genişlemek, yayılmak"),
            ("expectation", "beklenti, ummak"),
            ("experience", "deneyim, tecrübe"),
            ("expert", "uzman, bilirkişi"),
            ("explain", "açıklamak"),
            ("explode", "patlamak, havaya uçurmak"),
            ("exploit", "sömürmek, yararlanmak"),
            ("expose", "açığa çıkarmak, ifşa etmek"),
            ("extend", "uzatmak, genişletmek"),
            ("external", "dış, harici"),
            ("extract", "çıkarmak, özünü almak"),
            ("facilitate", "kolaylaştırmak, olanak sağlamak"),
            ("factor", "faktör, etken"),
            ("feature", "özellik, nitelik"),
            ("federal", "federal, merkezî hükümetle ilgili"),
            ("figure", "rakam, figür"),
            ("finalize", "sonlandırmak, tamamlamak"),
            ("finance", "finans, mali işleme ilişkin"),
            ("fit", "(1) uymak (2) uygun, sağlıklı"),
            ("fix", "onarmak, düzeltmek"),
            ("focus", "odaklanmak, dikkat vermek"),
            ("force", "kuvvet, zorlamak"),
            ("form", "biçim, şekil"),
            ("formulate", "formüle etmek, oluşturmak"),
            ("foundation", "temel, kuruluş"),
            ("framework", "çerçeve, çatı"),
            ("function", "(1) işlev, fonksiyon (2) işlev görmek"),
            ("generate", "üretmek, meydana getirmek"),
            ("genuine", "gerçek, samimi, içten"),
            ("global", "küresel, evrensel"),
            ("goal", "hedef, amaç"),
            ("govern", "yönetmek, idare etmek"),
            ("grace", "zarafet, incelik"),
            ("grant", "bağışlamak, hibe, vermek"),
            ("guarantee", "garanti etmek, teminat"),
            ("guidance", "rehberlik, yönlendirme"),
            ("habit", "alışkanlık"),
            ("handle", "(1) tutmak, ele almak (2) başa çıkmak"),
            ("healthy", "sağlıklı"),
            ("highlight", "vurgulamak, öne çıkarmak"),
            ("historical", "tarihi, tarihsel"),
            ("hold", "tutmak, (1) gerçekleştirmek (bir etkinlik vb)"),
            ("hope", "umut, ümit"),
            ("identify", "tanımlamak, belirlemek"),
            ("ignore", "görmezden gelmek, ihmal etmek"),
            ("impact", "etki, darbe"),
            ("implement", "uygulamak, hayata geçirmek"),
            ("imply", "ima etmek, anlamına gelmek"),
            ("impose", "yüklemek, zorla kabul ettirmek"),
            ("improve", "geliştirmek, iyileştirmek"),
            ("include", "dahil etmek"),
            ("increase", "artırmak, çoğaltmak"),
            ("indicate", "belirtmek, göstermek"),
            ("individual", "bireysel, şahıs"),
            ("influence", "etki, tesir"),
            ("inform", "bilgilendirmek"),
            ("initial", "ilk, başlangıç"),
            ("initiate", "başlatmak, girişimde bulunmak"),
            ("injure", "yaralamak, incitmek"),
            ("innovation", "yenilik, buluş"),
            ("inquire", "sormak, araştırmak"),
            ("inspire", "ilham vermek, teşvik etmek"),
            ("insist", "ısrar etmek"),
            ("instance", "örnek, olay"),
            ("instruct", "talimat vermek, öğretmek"),
            ("instrument", "alet, araç"),
            ("integrate", "bütünleştirmek, entegre etmek"),
            ("intelligence", "zeka, akıl, anlayış"),
            ("interact", "etkileşimde bulunmak"),
            ("interfere", "müdahale etmek"),
            ("internal", "iç, dahili"),
            ("interpret", "yorumlamak"),
            ("interview", "görüşme, mülakat"),
            ("introduce", "tanıtmak"),
            ("invest", "yatırım yapmak"),
            ("investigate", "araştırmak, soruşturmak"),
            ("involve", "dahil etmek"),
            ("issue", "sorun, mesele, yayımlamak"),
            ("justify", "haklı çıkarmak, gerekçelendirmek"),
            ("keep", "tutmak, saklamak"),
            ("label", "etiket, damga"),
            ("labor", "iş, emek, çalışma"),
            ("lack", "eksiklik, yokluk"),
            ("launch", "(1) başlatmak (2) fırlatmak"),
            ("lead", "(1) öncülük etmek (2) yönetmek"),
            ("learning", "öğrenme"),
            ("legal", "yasal, hukuki"),
            ("leisure", "boş zaman, dinlenme"),
            ("level", "seviye, düzey, kat"),
            ("liberal", "liberal, serbest düşünen"),
            ("license", "lisans, ruhsat"),
            ("link", "bağlantı, bağlamak"),
            ("locate", "bulmak, yerleştirmek"),
            ("logic", "mantık, akıl yürütme"),
            ("maintain", "sürdürmek, korumak"),
            ("major", "büyük, ana, başlıca"),
            ("manipulate", "(1) bir şeyi veya bir durumu ustaca kontrol etmek (2) yönlendirmek"),
            ("manufacture", "imal etmek, üretmek"),
            ("mechanism", "mekanizma, işlem"),
            ("media", "medya, iletişim araçları"),
            ("medical", "tıbbi, sağlıkla ilgili"),
            ("memory", "bellek, hafıza"),
            ("mental", "zihinsel, akli"),
            ("method", "yöntem, tarz"),
            ("migrate", "göç etmek"),
            ("minimum", "en az, en düşük"),
            ("modify", "değiştirmek, uyarlamak"),
            ("monitor", "izlemek, gözlemlemek"),
            ("motive", "(1) motivasyon, dürtü (2) sebep"),
            ("move", "hareket etmek, taşımak"),
            ("multiple", "çoklu, birden fazla"),
            ("narrow", "daraltmak, dar"),
            ("navigate", "yön bulmak, sefer yapmak"),
            ("negotiate", "müzakere etmek, pazarlık yapmak"),
            ("network", "ağ, şebeke"),
            ("neutral", "tarafsız, nötr"),
            ("observe", "gözlemlemek, izlemek"),
            ("obtain", "elde etmek, almak"),
            ("obvious", "belli, açık"),
            ("occur", "meydana gelmek, oluşmak"),
            ("operate", "işletmek, çalıştırmak"),
            ("opportunity", "fırsat, olanak"),
            ("oppose", "karşı çıkmak, muhalefet etmek"),
            ("option", "seçenek"),
            ("organize", "düzenlemek, organize etmek"),
            ("output", "çıktı, verim"),
            ("overall", "genel, toplam"),
            ("overcome", "üstesinden gelmek"),
            ("participate", "katılmak, iştirak etmek"),
            ("partner", "ortak, iş birliği yapmak"),
            ("pattern", "desen, örüntü"),
            ("perceive", "algılamak, sezmek"),
            ("perform", "performans göstermek, gerçekleştirmek"),
            ("persist", "ısrar etmek, kalıcı olmak"),
            ("persuade", "ikna etmek, inandırmak"),
            ("physical", "fiziksel, bedensel"),
            ("plan", "plan, taslak"),
            ("policy", "politika, ilke"),
            ("positive", "olumlu, pozitif"),
            ("potential", "potansiyel"),
            ("predict", "tahmin etmek, öngörmek"),
            ("preference", "tercih, öncelik"),
            ("present", "(1) mevcut (2) sunmak"),
            ("preserve", "korumak, muhafaza etmek"),
            ("prevent", "engel olmak, önlemek"),
            ("previous", "önceki, geçmiş"),
            ("primary", "birincil, ana, temel"),
            ("principle", "ilke, prensip"),
            ("priority", "öncelik, öncelikli durum"),
            ("proceed", "ilerlemek, devam etmek"),
            ("process", "süreç, işlem"),
            ("produce", "üretmek, meydana getirmek"),
            ("product", "ürün, mal"),
            ("professional", "profesyonel, uzman"),
            ("program", "program, yazılım"),
            ("project", "proje, plan"),
            ("promote", "terfi ettirmek, tanıtım yapmak"),
            ("proof", "kanıt, ispat"),
            ("property", "mülk, malvarlık"),
            ("propose", "öneride bulunmak, teklif etmek"),
            ("protect", "korumak, muhafaza etmek"),
            ("prove", "kanıtlamak, ispat etmek"),
            ("provide", "sağlamak, temin etmek"),
            ("publish", "yayımlamak, yayınlamak"),
            ("qualify", "nitelik kazanmak, yeterli olmak"),
            ("quality", "kalite, nitelik"),
            ("quantity", "miktar, sayı"),
            ("range", "aralık, çeşitlilik"),
            ("react", "tepki vermek"),
            ("realize", "farkına varmak, gerçekleştirmek"),
            ("recognize", "tanımak, kabul etmek"),
            ("reduce", "azaltmak, indirmek"),
            ("reflect", "yansıtmak, aksettirmek"),
            ("reform", "reform, düzeltmek"),
            ("regulate", "düzenlemek, kontrol etmek"),
            ("relate", "ilişkili olmak, bağlamak"),
            ("release", "serbest bırakmak, yayınlamak"),
            ("relevant", "ilgili, alaka düzeyinde"),
            ("rely", "güvenmek, dayanmak"),
            ("remove", "çıkarmak, kaldırmak"),
            ("replace", "değiştirmek, yer değiştirmek"),
            ("require", "gerektirmek, zorunlu kılmak"),
            ("research", "araştırma, inceleme"),
            ("respond", "cevap vermek, yanıtlamak"),
            ("restore", "geri getirmek, onarmak"),
            ("restrict", "kısıtlamak, sınırlamak"),
            ("result", "sonuç, netice"),
            ("retain", "tutmak, korumak"),
            ("reveal", "açığa çıkarmak, ifşa etmek"),
            ("review", "gözden geçirmek, değerlendirmek"),
            ("revise", "gözden geçirmek, düzeltmek"),
            ("role", "rol, görev"),
            ("rule", "kural, hüküm"),
            ("run", "çalıştırmak, koşmak"),
            ("sample", "örnek, numune"),
            ("satisfy", "tatmin etmek, memnun etmek"),
            ("schedule", "program, takvim"),
            ("scope", "kapsam, alan"),
            ("search", "aramak, araştırmak"),
            ("secure", "güvence altına almak, sağlamak"),
            ("seek", "aramak, talep etmek"),
            ("select", "seçmek, belirlemek"),
            ("separate", "ayırmak, ayrı"),
            ("serve", "hizmet etmek, sunmak"),
            ("service", "hizmet, servis"),
            ("shift", "kaydırmak, değiştirmek"),
            ("significant", "önemli, anlamlı"),
            ("similar", "benzer, aynı"),
            ("simplify", "basitleştirmek, sadeleştirmek"),
            ("site", "alan, yer"),
            ("skill", "beceri, yetenek"),
            ("socialize", "sosyalleşmek"),
            ("source", "kaynak, kaynak sağlamak"),
            ("specific", "belirli, özel"),
            ("structure", "yapı, yapılandırmak"),
            ("study", "incelemek, çalışmak"),
            ("submit", "sunmak, teslim etmek"),
            ("succeed", "başarılı olmak, başarmak"),
            ("support", "desteklemek, yardım etmek"),
            ("survey", "anket, araştırma yapmak"),
            ("survive", "hayatta kalmak, sürdürmek"),
            ("system", "sistem, düzen"),
            ("target", "hedef, amaç"),
            ("team", "ekip, takım"),
            ("technology", "teknoloji"),
            ("tend", "eğilmek, meyletmek"),
            ("term", "terim, dönem"),
            ("test", "test etmek, sınav"),
            ("theory", "teori, kuram"),
            ("threaten", "tehdit etmek, korkutmak"),
            ("time", "zaman, süre"),
            ("topic", "konu, başlık"),
            ("trade", "ticaret, takas"),
            ("training", "eğitim, antrenman"),
            ("transfer", "transfer etmek, nakletmek"),
            ("transform", "dönüştürmek, değiştirmek"),
            ("trend", "eğilim, akım"),
            ("trust", "güven, itimat"),
            ("unique", "benzersiz, eşsiz"),
            ("unite", "birleştirmek"),
            ("update", "güncellemek"),
            ("utilize", "kullanmak, faydalanmak"),
            ("validate", "geçerli kılmak, onaylamak"),
            ("vary", "değişiklik göstermek"),
            ("volunteer", "gönüllü olarak çalışmak"),
            ("waste", "israf, atık"),
            ("weaken", "zayıflatmak, güçsüzleştirmek"),
            ("witness", "tanık olmak, şahitlik etmek"),
            ("yield", "üretmek, sağlamak"),
            ("Inquiry", "Araştırma"),
            ("Relation", "İlişki"),
            ("Important", "Önemli"),
            ("Conflict", "Çatışma, anlaşmazlık"),
            ("Challenge", "Zorluk, güçlük"),
            ("Division", "Paylaştırma, bölüşme"),
            ("Implication", "Muhtemel etki/sonuç"),
            ("Drawback", "Sorun, sakınca"),
            ("Requirement", "Gereksinim, ihtiyaç"),
            ("Save", "Kurtarmak"),
            ("Convenience", "Uygunluk, kolaylık"),
            ("Enhance", "Geliştirmek, artırmak"),
            ("Detect", "Tespit etmek"),
            ("Manipulate", "Yönlendirmek"),
            ("Progress", "Gelişmek, ilerlemek"),
            ("Transmit", "Aktarmak, iletmek"),
            ("Inherit", "Miras olarak almak"),
            ("Surround", "Çevrelemek, kuşatmak"),
            ("Protect", "Korumak"),
            ("Delicate", "Hassas, zayıf"),
            ("Excessive", "Aşırı, fazla"),
            ("Vigorous", "Baskın, güçlü"),
            ("Elaborate", "Karmaşık, ayrıntılı"),
            ("Swift", "Hızlı, çabuk"),
            ("Mutual", "Karşılıklı, ortak"),
            ("Convincing", "İkna edici, inandırıcı"),
            ("Drastic", "Ani, sert, güçlü"),
            ("Pure", "Sade, saf"),
            ("Deny", "İnkar etmek, geri çevirmek"),
            ("Hinder", "Engellemek"),
            ("Suspend", "Askıya almak"),
            ("Create", "Yaratmak, icat etmek"),
            ("Eliminate", "Yok etmek, ortadan kaldırmak"),
            ("Encompass", "Kapsamak, içermek"),
            ("Distract", "Dikkatini dağıtmak"),
            ("Solution", "Çözüm"),
            ("Make up for", "Telafi etmek"),
            ("Look up to", "Hayran olmak"),
            ("Come up with", "Önermek"),
            ("Let", "İzin vermek"),
            ("Alter", "Değiştirmek"),
            ("Research", "Araştırma"),
            ("Define", "Tanımlamak, betimlemek"),
            ("Consume", "Tüketmek, harcamak"),
            ("Responsible", "Sorumlu"),
            ("Prone", "Savunmasız, zayıf"),
            ("Allow", "İzin vermek, olanak sağlamak"),
            ("Provide", "Sağlamak"),
            ("Destroy", "Yok etmek"),
            ("Significantly", "Önemli ölçüde, çok"),
            ("Reduce", "Azalmak, azaltmak"),
            ("Burden", "Yük"),
            ("Impact", "Etki"),
            ("Confine", "Sınırlandırmak"),
            ("Respond", "Karşılık vermek"),
            ("Uncover", "Açığa çıkarmak, ortaya koymak"),
            ("Reverse", "Engellemek, tersine çevirmek"),
            ("Modify", "Değiştirmek"),
            ("Vague", "Belirsiz"),
            ("Partial", "Kısmen"),
            ("Notable", "Kayda değer"),
            ("Predict", "Tahmin etmek, öngörmek"),
            ("Experience", "Tecrübe etmek"),
            ("Intense", "Yoğun"),
            ("Evidence", "Kanıt"),
            ("Flourish", "Gelişmek, ilerlemek"),
            ("Lead to", "Sebep olmak, yol açmak"),
            ("Objective", "Amaç, hedef"),
            ("Accelerate", "Hızlandırmak"),
            ("Available", "Mevcut"),
            ("Resist", "Direnmek"),
            ("Rule out", "Hesaba katmamak"),
            ("Indicate", "Göstermek, ortaya koymak"),
            ("Evaluate", "Değerlendirmek"),
            ("Look after", "Bakmak, ilgilenmek"),
            ("Make up", "Oluşturmak"),
            ("Obtain", "Elde etmek"),
            ("Harmful", "Zararlı"),
            ("Increase", "Artmak, artırmak"),
            ("Include", "İçermek, kapsamak"),
            ("Attract", "Etkilemek"),
            ("Depend on", "Bağlı olmak"),
            ("Develop", "Gelişmek, geliştirmek"),
            ("Explore", "Keşfetmek, aramak"),
            ("Establish", "Kurmak, inşa etmek"),
            ("Influence", "Etki"),
            ("Solve", "Çözmek"),
            ("Propose", "Önermek, tavsiye etmek"),
            ("Approve", "Onaylamak"),
            ("Expect", "Ummak"),
            ("Affect", "Etkilemek"),
            ("Cause", "Sebep olmak, yol açmak"),
            ("Determine", "Belirlemek"),
            ("Hazardous", "Tehlikeli"),
            ("Desire", "Arzulamak"),
            ("Vulnerable", "Savunmasız, hassas"),
            ("Struggle", "Mücadele"),
            ("Face", "Yüzleşmek, karşılaşmak"),
            ("Willing", "İstekli, hevesli"),
            ("Escape", "Kurtulmak, kaçmak"),
            ("Measure", "Tedbir, önlem"),
            ("Observe", "Gözlemlemek"),
            ("Incredible", "İnanılmaz"),
            ("Force", "Güç, kuvvet"),
            ("Examine", "İncelemek"),
            ("Extensively", "Kapsamlı bir şekilde"),
            ("Attention", "Dikkat"),
            ("Notorious", "Namı kötü, kötü şöhretli"),
            ("Avoid", "Kaçınmak"),
            ("Gain", "Kazanmak, elde etmek"),
            ("Deliberate", "Kasten, bilerek"),
            ("Diverse", "Çeşitli, farklı"),
            ("Support", "Desteklemek"),
            ("Follow", "Takip etmek"),
            ("Contribute to", "Katkıda bulunmak"),
            ("Require", "Gerektirmek"),
            ("Benefit", "Fayda, yarar"),
            ("Sustain", "Sürdürmek"),
            ("Prompt", "Hızlı, çabuk"),
            ("Deal with", "Ele almak, ilgilenmek"),
            ("Notice", "Fark etmek"),
            ("Attend", "Katılmak"),
            ("Reputation", "Ün, şöhret"),
            ("Represent", "Temsil etmek"),
            ("Assume", "Varsaymak, farz etmek"),
            ("Massive", "Büyük, devasa"),
            ("Exposure", "Maruz kalma"),
            ("Addicted", "Bağımlı"),
            ("Cope with", "Ele almak, ilgilenmek"),
            ("Describe", "Tasvir etmek"),
            ("Reach", "Erişmek, ulaşmak"),
            ("Sound", "Mantıklı"),
            ("Display", "Göstermek, ortaya koymak"),
            ("Compare", "Karşılaştırmak"),
            ("Virtually", "Yaklaşık"),
            ("Cost", "Maliyet"),
            ("Advance", "Gelişme, ilerleme"),
            ("Process", "Süreç"),
            ("Accompany", "Eşlik etmek"),
            ("Legitimate", "Yasal, meşru"),
            ("Merely", "Sadece, yalnız"),
            ("Distinguish", "Ayırt etmek"),
            ("Pressure", "Baskı"),
            ("Quit", "Bırakmak"),
            ("Incentive", "Teşvik"),
            ("Purpose", "Amaç, hedef"),
            ("Feature", "Özellik"),
            ("Primary", "Ana, temel"),
            ("Obstacle", "Engel"),
            ("Compelling", "İkna edici, inandırıcı"),
            ("Ambiguous", "Belirsiz, net olmayan"),
            ("Discover", "Keşfetmek"),
            ("Accept", "Kabul etmek"),
            ("Conduct", "Uygulamak, yapmak"),
            ("Bring about", "Sebep olmak"),
            ("Turn down", "Reddetmek, geri çevirmek"),
            ("Offer", "Tavsiye etmek, önermek"),
            ("View", "Görüş, bakış açısı"),
            ("Believe", "İnanmak"),
            ("Emerge", "Ortaya çıkmak"),
            ("Assert", "İleri sürmek, iddia etmek"),
            ("Means", "Yol, yöntem"),
            ("Pattern", "Şekil, kalıp, desen"),
            ("Endure", "Katlanmak"),
            ("Contain", "İçermek"),
            ("Demand", "Talep, istek"),
            ("Rely on", "Güvenmek, bağlı olmak"),
            ("Call off", "İptal etmek"),
            ("Decline", "Azalmak"),
            ("Prove", "İspatlamak"),
            ("Promote", "Geliştirmek, artırmak"),
            ("Utilize", "Kullanmak, faydalanmak"),
            ("Encourage", "Teşvik etmek"),
            ("Relatively", "Nispeten"),
            ("Consequence", "Sonuç"),
            ("Comprehend", "Anlamak"),
            ("Accessible", "Erişilebilir, mevcut"),
            ("Constitute", "Oluşturmak"),
            ("Regard", "Dikkate almak, düşünmek"),
            ("Emphasize", "Vurgulamak"),
            ("Impose", "Uygulamak, zorlamak"),
            ("Involve", "Kapsamak, içermek"),
            ("Gather", "Toplamak"),
            ("Secure", "Güvence altına almak"),
            ("Achieve", "Başarmak, ulaşmak"),
            ("Implicit", "Açıkça ifade edilmeyen"),
            ("Expectation", "Beklenti"),
            ("Subject", "Konu, nesne"),
            ("Transfer", "Transfer etmek"),
            ("Enable", "Olanak sağlamak"),
            ("Formulate", "Şekil vermek, oluşturmak"),
            ("Display", "Göstermek"),
            ("Adjust", "Ayarlamak"),
            ("Anticipate", "Ön görmek"),
            ("Overcome", "Üstesinden gelmek"),
            ("Focus", "Odaklanmak"),
            ("Attribute", "Bağlamak, yormak"),
            ("Critical", "Eleştirici, kritik"),
            ("Brief", "Kısa, öz"),
            ("Context", "Bağlam, durum"),
            ("Generate", "Oluşturmak, üretmek"),
            ("Isolate", "Yalnız bırakmak"),
            ("Interact", "Etkileşimde bulunmak"),
            ("Formalize", "Resmi hale getirmek"),
            ("Appropriate", "Uygun, elverişli"),
            ("Perceive", "Algılamak"),
            ("Conclude", "Sonuçlandırmak"),
            ("Perform", "Gerçekleştirmek"),
            ("Focus on", "Üzerine yoğunlaşmak"),
            ("Prompt", "Hızlandırmak"),
            ("Minimize", "En aza indirmek"),
            ("Enforce", "Uygulamak, zorlamak"),
            ("Assume", "Üstlenmek, farz etmek"),
            ("Shift", "Değişim"),
            ("Encounter", "Karşılaşmak"),
            ("Impose", "Uygulamak, zorlamak"),
            ("Contribute", "Katkıda bulunmak"),
            ("Verify", "Doğrulamak"),
            ("Intervene", "Müdahale etmek"),
            ("Undergo", "Geçirmek, maruz kalmak"),
            ("Acquire", "Elde etmek"),
            ("Induce", "Sebep olmak"),
            ("Promote", "Teşvik etmek"),
            ("Benefit", "Yarar sağlamak"),
            ("Adapt", "Uyum sağlamak"),
            ("Examine", "İncelemek"),
            ("Translate", "Çevirmek"),
            ("Validate", "Doğrulamak"),
            ("Illustrate", "Örneklerle açıklamak"),
            ("Require", "Gerektirmek"),
            ("Allocate", "Tahsis etmek"),
            ("Advocate", "Savunmak"),
            ("Elevate", "Yükseltmek"),
            ("Collaborate", "İş birliği yapmak"),
            ("Enable", "Olanak tanımak"),
            ("Maintain", "Sürdürmek"),
            ("Interpret", "Yorumlamak"),
            ("Complement", "Tamamlamak, tamamlayıcı olmak"),
            ("Afford", "Göze almak, maddi durumu karşılamak"),
            ("Obligate", "Zorlamak, yükümlü kılmak"),
            ("Clarify", "Açıklığa kavuşturmak"),
            ("Obtain", "Elde etmek"),
            ("Facilitate", "Kolaylaştırmak"),
            ("Represent", "Temsil etmek"),
            ("Encounter", "Karşılaşmak"),
            ("Conduct", "Yönetmek, düzenlemek"),
            ("Challenge", "Zorluk çıkarmak"),
            ("Utilize", "Kullanmak, faydalanmak"),
            ("Attribute", "Atfetmek"),
            ("Exceed", "Aşmak"),
            ("Advocate", "Savunmak"),
            ("Exclude", "Hariç tutmak, dışlamak"),
            ("Advocate", "Savunmak"),
            ("Optimize", "Optimize etmek"),
            ("Distribute", "Dağıtmak"),
            ("Consult", "Danışmak"),
            ("Encounter", "Karşılaşmak"),
            ("Conform", "Uymak"),
            ("Suggest", "Önermek"),
            ("Notify", "Bilgilendirmek"),
            ("Critique", "Eleştirmek"),
            ("Summarize", "Özetlemek"),
            ("Collaborate", "İşbirliği yapmak"),
            ("Elaborate", "Ayrıntılandırmak"),
            ("Validate", "Doğrulamak"),
            ("Enforce", "Zorlamak, uygulamak"),
            ("Outline", "Taslak oluşturmak"),
            ("Transition", "Geçiş yapmak"),
            ("Attribute", "Atfetmek"),
            ("Perceive", "Algılamak"),
            ("Attend", "Katılmak"),
            ("Exclude", "Hariç tutmak"),
            ("Promote", "Teşvik etmek"),
            ("Require", "Gerektirmek"),
            ("Integrate", "Bütünleştirmek"),
            ("Advance", "Geliştirmek, ilerletmek"),
            ("Constrain", "Kısıtlamak"),
            ("Coordinate", "Koordine etmek"),
            ("Maintain", "Sürdürmek"),
            ("Undertake", "Üstlenmek"),
            ("Suggest", "Önermek"),
            ("Overcome", "Üstesinden gelmek"),
            ("Address", "Ele almak"),
            ("Contribute", "Katkıda bulunmak"),
            ("Investigate", "Araştırmak"),
            ("Influence", "Etkilemek"),
            ("Emphasize", "Vurgulamak"),
            ("Generate", "Oluşturmak"),
            ("Allocate", "Tahsis etmek"),
            ("Strengthen", "Güçlendirmek"),
            ("Pursue", "Peşinden koşmak"),
            ("Evaluate", "Değerlendirmek"),
            ("Examine", "İncelemek"),
            ("Restrict", "Sınırlamak"),
            ("Encounter", "Karşılaşmak"),
            ("Shape", "Şekil vermek"),
            ("Involve", "Kapsamak"),
            ("Reinforce", "Güçlendirmek"),
            ("Critique", "Eleştiri yapmak"),
            ("Propose", "Teklif etmek"),
            ("Uncover", "Ortaya çıkarmak"),
            ("Illustrate", "Açıklamak, örnek vermek"),
            ("Implement", "Uygulamak"),
            ("Allocate", "Tahsis etmek"),
            ("Transform", "Dönüştürmek"),
            ("Integrate", "Bütünleştirmek"),
            ("Utilize", "Faydalanmak"),
            ("Acquire", "Elde etmek"),
            ("Foster", "Geliştirmek"),
            ("Specify", "Belirlemek"),
            ("Assess", "Değerlendirmek"),
            ("Reinforce", "Güçlendirmek"),
            ("Facilitate", "Kolaylaştırmak"),
            ("Supplement", "Tamamlamak"),
            ("Address", "Ele almak"),
            ("Recognize", "Tanımak, fark etmek"),
            ("Challenge", "Zorluk çıkarmak"),
            ("Pursue", "Peşinden koşmak"),
            ("Analyze", "Analiz etmek"),
            ("Illustrate", "Açıklamak, örnek vermek"),
            ("Collaborate", "İşbirliği yapmak"),
            ("Validate", "Geçerli kılmak"),
            ("Emphasize", "Vurgulamak"),
            ("Confirm", "Onaylamak"),
            ("Conduct", "Yapmak, uygulamak"),
            ("Generate", "Üretmek, oluşturmak"),
            ("Propose", "Öneride bulunmak"),
            ("Analyze", "İncelemek, analiz etmek"),
            ("Review", "Gözden geçirmek"),
            ("Conclude", "Sonuçlandırmak"),
            ("Modify", "Değiştirmek"),
            ("Assess", "Değerlendirmek"),
            ("Critique", "Eleştiri yapmak"),
            ("Clarify", "Aydınlatmak, netleştirmek"),
            ("Arrange", "Düzenlemek"),
            ("Evaluate", "Değerlendirmek"),
            ("Sustain", "Sürdürmek"),
            ("Minimize", "En aza indirmek"),
            ("Enforce", "Uygulamak"),
            ("Encourage", "Teşvik etmek"),
            ("Respond", "Yanıt vermek"),
            ("Consider", "Düşünmek, değerlendirmek"),
            ("Elaborate", "Ayrıntılandırmak"),
            ("Incorporate", "Dahil etmek"),
            ("Investigate", "Araştırmak"),
            ("Propose", "Teklif etmek"),
            ("Assess", "Değerlendirmek"),
            ("Seek", "Aramak, istemek"),
            ("Reveal", "Ortaya çıkarmak"),
            ("Dedicate", "Adamak, ithaf etmek"),
            ("Emerge", "Ortaya çıkmak"),
            ("Confirm", "Onaylamak"),
            ("Alter", "Değiştirmek"),
            ("Combine", "Birleştirmek"),
            ("Maintain", "Sürdürmek"),
            ("Project", "Proje, tasarlamak"),
            ("Respond", "Yanıt vermek"),
            ("Accompany", "Eşlik etmek"),
            ("Engage", "İlgilendirmek"),
            ("Validate", "Doğrulamak"),
            ("Initiate", "Başlatmak"),
            ("Resolve", "Çözmek"),
            ("Evaluate", "Değerlendirmek"),
            ("Modify", "Değiştirmek"),
            ("Specify", "Belirlemek"),
            ("Collaborate", "İş birliği yapmak"),
            ("Involve", "Kapsamak"),
            ("Overcome", "Üstesinden gelmek"),
            ("Assess", "Değerlendirmek"),
            ("Confirm", "Onaylamak"),
            ("Utilize", "Kullanmak"),
            ("Execute", "Uygulamak, icra etmek"),
            ("Maintain", "Sürdürmek"),
            ("Incorporate", "Dahil etmek"),
            ("Contribute", "Katkıda bulunmak"),
            ("Propose", "Teklif etmek"),
            ("Coordinate", "Koordine etmek"),
            ("Emphasize", "Vurgulamak"),
            ("Identify", "Tanımlamak"),
            ("Adapt", "Uyum sağlamak"),
            ("Cultivate", "Geliştirmek, yetiştirmek"),
            ("Investigate", "Araştırmak"),
            ("Conclude", "Sonuçlandırmak"),
            ("Allocate", "Tahsis etmek"),
            ("Maintain", "Sürdürmek"),
            ("Formulate", "Oluşturmak"),
            ("Represent", "Temsil etmek"),
            ("Improve", "İyileştirmek"),
            ("Explore", "Keşfetmek"),
            ("Clarify", "Açıklığa kavuşturmak"),
            ("Predict", "Tahmin etmek"),
            ("Capture", "Yakalamak")


        ]
        self.current_index = None  # Rastgele kelime indeksi için başlangıç

        self.init_ui()
        self.next_word()  # İlk kelimeyi göster

    def init_ui(self):
        self.layout = QVBoxLayout()

        self.word_label = QLabel()
        self.word_label.setAlignment(Qt.AlignCenter)  # Kelimeyi ortala
        self.word_label.setStyleSheet("font-size: 30px;")  # Kelime boyutunu büyüt
        self.layout.addWidget(self.word_label)

        # Butonlar için yatay bir düzen oluştur
        self.button_layout = QHBoxLayout()

        self.turkish_button = QPushButton("Türkçesini Göster")
        self.turkish_button.clicked.connect(self.show_turkish)
        self.button_layout.addWidget(self.turkish_button)

        self.english_button = QPushButton("İngilizcesini Göster")
        self.english_button.clicked.connect(self.show_english)
        self.button_layout.addWidget(self.english_button)

        self.next_button = QPushButton("Sıradaki Kelime")
        self.next_button.clicked.connect(self.next_word)
        self.button_layout.addWidget(self.next_button)

        self.layout.addLayout(self.button_layout)

        # Uygulama pencere boyutunu ayarla
        self.setLayout(self.layout)
        self.setWindowTitle('YDS Kelime Öğrenme Uygulaması')
        self.resize(400, 300)  
        self.center()  
        self.show()

    def center(self):
        qr = self.frameGeometry()
        cp = self.screen().availableGeometry().center()
        qr.moveCenter(cp)
        self.move(qr.topLeft())

    def show_turkish(self):
        if self.current_index is not None:
            turkish_word = self.words[self.current_index][1]
            self.word_label.setText(turkish_word)

    def show_english(self):
        if self.current_index is not None:
            english_word = self.words[self.current_index][0]
            self.word_label.setText(english_word)

    def next_word(self):
        self.current_index = random.randint(0, len(self.words) - 1) 
        self.word_label.setText(self.words[self.current_index][0])  

if __name__ == '__main__':
    app = QApplication(sys.argv)
    ex = VocabularyApp()
    sys.exit(app.exec_())
